### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by mitchhankins01** [m-coding/fe-05-2-nutrition-tracker#1]
Hi,

I love this app you created, I wanted to ask (before actually doing it) if this is something I am allowed to integrate in my own website. I could not find any contact information, so I hope this way is a good way to ask.

Thanks!

**Comment by m-coding** [comment]
Hello! Sorry for taking a while to respond, was on holiday. Yeah, I don't mind, I love seeing what others do! Maybe a link back to the repo so others can find it? -M

**Comment by mitchhankins01** [comment]
Sounds good! Thank you :)
